### ISSUE TITLE
twrp_device_xiaoxun_MiKidsSmartWatch_5C

### ISSUE THREAD

**Issue by ogelyk** [ZH-XiJun/twrp_device_xiaoxun_MiKidsSmartWatch_4PRO#1]
Hello @ZH-XiJun,

I'm writing here because I don't have QQ.
I am looking for TWRP for Mi Kids SmartWatch 5C. Can you please help me? 
In one of your instructions I noticed that you have a firmware dump from 3C - maybe you know where to get the firmware for 5C and 6C?

Thank you

**Comment by ZH-XiJun** [comment]
now the firmware of mitu 5c has been made public by XK. you can register a QQ account and download it.
The recovery partition of 5c is too small to flash twrp image. maybe someone can solve it.
I hope these answers can help you,
Best wishes.
